### ISSUE TITLE
Problemas com o placar

### ISSUE THREAD

**Issue by netsoncavina** [yurilimadev/TBBT_pedra_papel_tesoura_lagarto_spock#1]
<h1> Apesar de ser melhor de 5, que deveria acabar quando alguém atingir 3 pontos, a partida continua sem resetar a pontuação </h1>

![image](https://github.com/user-attachments/assets/ef0b6723-7e30-4e54-823c-6335f9771764)

**Comment by netsoncavina** [comment]
Corrigido no PR: https://github.com/yurilimadev/TBBT_pedra_papel_tesoura_lagarto_spock/pull/2

**Comment by yurilimadev** [comment]
Não tinha pego esse detalhe! Eu tava mesmo com dificuldade de resetar alguns conteúdo dentro dos elementos. DOM ainda é um mundo novo para mim! >.<
